// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/src/runtime/query_builder/query_builder.dart' as i2;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scheduleBlocks,
    tasks,
    subtasks,
    focusSessions,
    aiProviderConfigs,
    aiConversations,
    aiMessages,
    tasksScheduleBlockId,
    subtasksTaskOrder,
    scheduleBlocksStartTime,
    focusSessionsOneActive,
    focusSessionsCompletedAt,
    aiMessagesConversationOrder,
  ];
  late final Shape0 scheduleBlocks = Shape0(
      source: i0.VersionedTable(
        entityName: 'schedule_blocks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 tasks = Shape1(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_6,
          _column_1,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 subtasks = Shape2(
      source: i0.VersionedTable(
        entityName: 'subtasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_12,
          _column_1,
          _column_9,
          _column_13,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 focusSessions = Shape3(
      source: i0.VersionedTable(
        entityName: 'focus_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 aiProviderConfigs = Shape4(
      source: i0.VersionedTable(
        entityName: 'ai_provider_configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(provider_id)',
        ],
        columns: [
          _column_27,
          _column_28,
          _column_29,
          _column_30,
          _column_31,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 aiConversations = Shape5(
      source: i0.VersionedTable(
        entityName: 'ai_conversations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_27,
          _column_1,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 aiMessages = Shape6(
      source: i0.VersionedTable(
        entityName: 'ai_messages',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
          _column_37,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index tasksScheduleBlockId = i1.Index('tasks_schedule_block_id',
      'CREATE INDEX tasks_schedule_block_id ON tasks (schedule_block_id)');
  final i1.Index subtasksTaskOrder = i1.Index('subtasks_task_order',
      'CREATE INDEX subtasks_task_order ON subtasks (task_id, order_index)');
  final i1.Index scheduleBlocksStartTime = i1.Index(
      'schedule_blocks_start_time',
      'CREATE INDEX schedule_blocks_start_time ON schedule_blocks (start_time)');
  final i1.Index focusSessionsOneActive = i1.Index('focus_sessions_one_active',
      'CREATE UNIQUE INDEX focus_sessions_one_active ON focus_sessions (completed_at IS NULL) WHERE completed_at IS NULL');
  final i1.Index focusSessionsCompletedAt = i1.Index(
      'focus_sessions_completed_at',
      'CREATE INDEX focus_sessions_completed_at ON focus_sessions (completed_at)');
  final i1.Index aiMessagesConversationOrder = i1.Index(
      'ai_messages_conversation_order',
      'CREATE INDEX ai_messages_conversation_order ON ai_messages (conversation_id, sent_at, id)');
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get endTime =>
      columnsByName['end_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get source =>
      columnsByName['source']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isLocked =>
      columnsByName['is_locked']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_2(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('start_time', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_3(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('end_time', aliasedName, false,
        check: () =>
            i2.ComparableExpr((i0.VersionedTable.col<DateTime>('end_time')))
                .isBiggerThan((i0.VersionedTable.col<DateTime>('start_time'))),
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>('source', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<bool> _column_5(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_locked', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_locked" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scheduleBlockId =>
      columnsByName['schedule_block_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>('schedule_block_id', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES schedule_blocks (id) ON DELETE SET NULL'));
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('notes', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'\''));
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('priority', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('status', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_10(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('due_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_11(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression(
            'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)'));

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedSprints =>
      columnsByName['planned_sprints']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedSprints =>
      columnsByName['completed_sprints']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>('task_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES tasks (id) ON DELETE CASCADE'));
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('planned_sprints', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('1'));
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('completed_sprints', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>('order_index', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subtaskId =>
      columnsByName['subtask_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionType =>
      columnsByName['session_type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedDurationSec =>
      columnsByName['planned_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get segmentStartedAt =>
      columnsByName['segment_started_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get remainingSecAtSegmentStart =>
      columnsByName['remaining_sec_at_segment_start']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isPaused =>
      columnsByName['is_paused']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get actualDurationSec =>
      columnsByName['actual_duration_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get endedEarly =>
      columnsByName['ended_early']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>('task_id', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES tasks (id) ON DELETE SET NULL'));
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('subtask_id', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES subtasks (id) ON DELETE SET NULL'));
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('session_type', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('planned_duration_sec', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_20(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('started_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_21(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('segment_started_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
        'remaining_sec_at_segment_start', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<bool> _column_23(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_paused', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_paused" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<DateTime> _column_24(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('completed_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>('actual_duration_sec', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<bool> _column_26(String aliasedName) =>
    i1.GeneratedColumn<bool>('ended_early', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("ended_early" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultModel =>
      columnsByName['default_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseUrl =>
      columnsByName['base_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>('provider_id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('display_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('default_model', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('base_url', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_31(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_active', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_active" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get role =>
      columnsByName['role']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isError =>
      columnsByName['is_error']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isPending =>
      columnsByName['is_pending']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get sentAt =>
      columnsByName['sent_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>('conversation_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES ai_conversations (id) ON DELETE CASCADE'));
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>('role', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>('content', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_35(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_error', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_error" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<bool> _column_36(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_pending', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_pending" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<DateTime> _column_37(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('sent_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression(
            'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)'));
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from3To4: from3To4,
    ));
